name: Python Tracing Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run with GCP_RESOURCE_DETECTOR=true
      env:
        GCP_RESOURCE_DETECTOR: "true"
      run: python main.py
    
    - name: Run with GCP_RESOURCE_DETECTOR=false
      env:
        GCP_RESOURCE_DETECTOR: "false"
      run: python main.py 